

markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: 盐水冲茶
tagline: 尘世中一个迷途小菜鸟
description: Everything about Mukosame.
category: 分类
url: http://yscc.xyz
feed: /atom.xml
author_info: <a href="http://yscc.xyz">yscc</a>
